from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parents[1]
DEV = ROOT / "source/dev"
SHARED = DEV / "android-shared/src/main"
TV = DEV / "android-tv/src"


class MCPPlaybackAutomationTests(unittest.TestCase):
    def test_debug_control_receiver_exists_only_in_debug_source_set(self):
        debug_manifest = TV / "debug/AndroidManifest.xml"
        debug_receiver = TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DevTestReceiver.java"
        main_manifest = TV / "main/AndroidManifest.xml"
        self.assertTrue(debug_manifest.exists())
        self.assertTrue(debug_receiver.exists())
        self.assertIn("opensagetv.vibe.miniclient.DEBUG_CONTROL", debug_manifest.read_text(encoding="utf-8"))
        self.assertIn("DevTestReceiver", debug_manifest.read_text(encoding="utf-8"))
        self.assertNotIn("DevTestReceiver", main_manifest.read_text(encoding="utf-8"))

    def test_receiver_is_snapshot_based_not_callback_telemetry(self):
        text = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DevTestReceiver.java").read_text(encoding="utf-8")
        checks = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DebugAsyncPlayerChecks.java").read_text(encoding="utf-8")
        state = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DebugStateProvider.java").read_text(encoding="utf-8")
        self.assertIn('"snapshot".equals(op)', text)
        self.assertIn('"skip_check".equals(op)', text)
        self.assertIn("currentSageTimelineMs(mediaCmd, player)", checks)
        self.assertIn("MEDIACMD_GETMEDIATIME", state)
        self.assertIn("player.getBufferLeft()", state)
        self.assertIn("player.getLastFileReadPos()", state)
        self.assertIn("EventRouter.postCommand(client, command);", checks)
        self.assertNotIn("PlayerTelemetry", text)
        self.assertNotIn("addListener", text)
        self.assertNotIn("setOn", text)

    def test_receiver_can_set_player_stream_decode_and_gsy_preferences(self):
        text = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DevTestReceiver.java").read_text(encoding="utf-8")
        config = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DebugPlayerConfigCommands.java").read_text(encoding="utf-8")
        self.assertIn("DebugPlayerConfigCommands.configure(context, intent)", text)
        self.assertIn("PrefStore.Keys.default_player", config)
        self.assertIn("AndroidPrefStore.STREAMING_MODE", config)
        self.assertIn("PrefStore.Keys.decoding_method", config)
        self.assertIn("PrefStore.Keys.gsy_player_engine", config)
        self.assertIn("PrefStore.Keys.gsy_system_probe_enabled", config)
        self.assertIn('intent.getStringExtra("gsy_system_probe")', config)
        self.assertIn('intent.getStringExtra("wait_for_playback_before_first_osd")', config)
        self.assertIn("PrefStore.Keys.wait_for_playback_before_first_osd", config)
        self.assertIn("appliesNextPlayback=true", config)

    def test_wait_for_playback_before_first_osd_is_opt_in_and_player_osd_scoped(self):
        prefs = (SHARED / "res/xml/prefs.xml").read_text(encoding="utf-8")
        guard = (DEV / "core/src/main/java/opensagetv/vibe/miniclient/PlaybackStartupFrameGuard.java").read_text(encoding="utf-8")
        plugin = (DEV / "core/src/main/java/opensagetv/vibe/miniclient/MiniPlayerPlugin.java").read_text(encoding="utf-8")
        ogl = (SHARED / "java/opensagetv/vibe/miniclient/android/opengl/OpenGLRenderer.java").read_text(encoding="utf-8")
        gdx = (SHARED / "java/opensagetv/vibe/miniclient/android/gdx/MiniClientGDXRenderer.java").read_text(encoding="utf-8")
        self.assertIn('android:key="wait_for_playback_before_first_osd"', prefs)
        self.assertIn('android:defaultValue="false"', prefs)
        self.assertIn('hint.hasMenuLike("MediaPlayer OSD")', guard)
        self.assertIn("onPlaybackLoad(boolean enabled", guard)
        self.assertIn("MAX_HOLD_MS = 5000L", guard)
        self.assertIn("READY_RECHECK_MS = 50L", guard)
        self.assertIn("hasRenderedFirstVideoFrame()", plugin)
        for renderer in (ogl, gdx):
            self.assertIn("playbackStartupFrameGuard.deferFrame", renderer)
            self.assertIn("public void render()", renderer)
            self.assertIn("playbackStartupFrameGuard.isArmed()", renderer)
            self.assertIn("player.hasRenderedFirstVideoFrame()", renderer)
            self.assertIn("onPlaybackLoadStarted()", renderer)
            self.assertIn("playbackStartupFrameGuard.onPlaybackLoad", renderer)
            self.assertIn("PrefStore.Keys.wait_for_playback_before_first_osd", renderer)

        media_cmd = (DEV / "core/src/main/java/opensagetv/vibe/miniclient/MediaCmd.java").read_text(encoding="utf-8")
        self.assertGreaterEqual(media_cmd.count("notifyPlaybackLoadStarted();"), 3)
        self.assertIn("getUiRenderer().onPlaybackLoadStarted();", media_cmd)

        backends = {
            "media3": SHARED / "java/opensagetv/vibe/miniclient/android/video/media3/Media3MediaPlayerImpl.java",
            "legacy-exo": SHARED / "java/opensagetv/vibe/miniclient/android/video/exoplayer2/Exo2MediaPlayerImpl.java",
            "ijk": SHARED / "java/opensagetv/vibe/miniclient/android/video/ijkplayer/IJKMediaPlayerImpl.java",
            "gsy-system": SHARED / "java/opensagetv/vibe/miniclient/android/video/gsy/GSYSystemMediaPlayerImpl.java",
        }
        for name, path in backends.items():
            with self.subTest(backend=name):
                source = path.read_text(encoding="utf-8")
                self.assertIn("hasRenderedFirstVideoFrame()", source)
                self.assertIn("firstVideoFrameRendered = true", source)

        gsy = (SHARED / "java/opensagetv/vibe/miniclient/android/video/gsy/GSYMediaPlayerImpl.java").read_text(encoding="utf-8")
        self.assertIn("d().hasRenderedFirstVideoFrame()", gsy)

    def test_mcp_server_exposes_seek_automation_tools(self):
        server = (ROOT / "mcp/src/sagetv_dev_mcp/server.py").read_text(encoding="utf-8")
        for name in (
            "dev_player_state",
            "dev_set_player_config",
            "dev_search",
            "dev_open_search",
            "dev_wait_for_ime",
            "dev_type_text",
            "dev_input_text_keyboard",
            "dev_input_text_direct",
            "dev_hide_ime",
            "dev_player_control",
            "dev_frame_step",
            "dev_seek_relative",
            "dev_skip_forward",
            "dev_skip_backward",
            "dev_comskip",
            "dev_search_text",
            "dev_sage_command",
            "dev_sage_command_sequence",
            "dev_run_seek_check",
            "dev_run_relative_seek_check",
            "dev_run_comskip_check",
            "dev_wait_for_media_position",
            "dev_seek_time",
            "dev_server_seek_time",
            "dev_local_seek_absolute",
            "dev_test_checkpoint",
        ):
            self.assertIn(f"def {name}(", server)
        self.assertIn('adb.android_skip_check(', server)
        self.assertIn('commands,', server)
        self.assertIn('"measurement": "android_output_health_with_ui_timeline_context"', server)
        self.assertIn('"sageTimelineMs"', server)

    def test_frame_step_has_a_durable_physical_gate(self):
        script = (ROOT / "scripts/mcp_frame_step_test.py").read_text(encoding="utf-8")
        dev_script = (ROOT / "dev.sh").read_text(encoding="utf-8")
        self.assertIn('call_dict(client, "dev_frame_step"', script)
        self.assertIn('"server_frame_step_command"', script)
        self.assertIn('"server_frame_step_unsupported"', script)
        self.assertIn('health_videoDecoderKind', script)
        self.assertIn('mcp-frame-step-test)', dev_script)

    def test_mcp_seek_suite_calibrates_server_skip_intervals(self):
        script = (ROOT / "scripts/mcp_seek_suite.py").read_text(encoding="utf-8")
        self.assertIn('client, "ff", +1, args.calibrate_settle_ms', script)
        self.assertIn('client, "rew", -1, args.calibrate_settle_ms', script)
        self.assertIn('commands_for_delta(30_000, ff_ms, rew_ms)', script)
        self.assertIn('commands_for_delta(-10_000, ff_ms, rew_ms)', script)
        self.assertIn('rapid_targets = [30_000, 30_000, -10_000, 60_000, -30_000]', script)
        self.assertIn('SageTV timeline calibration:', script)
        self.assertIn('Rapid semantic expansion:', script)
        self.assertIn('--calibrate-timeline', script)
        self.assertIn('Timeline calibration skipped: PASS/FAIL is based on real video/audio output recovery', script)
        self.assertIn('rapid mixed FF/REW output-health stress', script)
        self.assertIn('dev_test_checkpoint', script)

    def test_mcp_seek_suite_allows_skip_interval_overrides(self):
        script = (ROOT / "scripts/mcp_seek_suite.py").read_text(encoding="utf-8")
        self.assertIn('--ff-ms', script)
        self.assertIn('--rew-ms', script)
        self.assertIn('--paced-delay-ms', script)
        self.assertIn('--calibration-quantum-ms', script)
        self.assertIn('--calibration-samples', script)
        self.assertIn('Optional timeline calibration: playback paused', script)
        self.assertIn('select_calibration_value', script)
        self.assertIn('all_attempts_ms', script)
        self.assertNotIn('cannot closely represent', script)

    def test_android_skip_check_returns_ui_timeline_difference(self):
        receiver = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DevTestReceiver.java").read_text(encoding="utf-8")
        checks = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DebugAsyncPlayerChecks.java").read_text(encoding="utf-8")
        adb = (ROOT / "mcp/src/sagetv_dev_mcp/adb.py").read_text(encoding="utf-8")
        server = (ROOT / "mcp/src/sagetv_dev_mcp/server.py").read_text(encoding="utf-8")
        self.assertIn("timelineBeforeMs", checks)
        self.assertIn("timelineAfterMs", checks)
        self.assertIn("timelineDeltaMs", checks)
        self.assertIn("playbackAdjustedDeltaMs", checks)
        executor = (
            ROOT
            / "source"
            / "dev"
            / "android-tv"
            / "src"
            / "debug"
            / "java"
            / "opensagetv"
            / "vibe"
            / "miniclient"
            / "android"
            / "tv"
            / "debug"
            / "DebugAsyncExecutor.java"
        ).read_text(encoding="utf-8")
        self.assertIn("SageTV-MCP-", executor)
        self.assertIn("def android_skip_check(", adb)
        self.assertIn('self.dev_control(\n            "skip_check"', adb)
        self.assertIn('result.get("playbackAdjustedDeltaMs"', server)


    def test_skip_check_verifies_real_video_audio_output_not_only_timeline(self):
        receiver = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DevTestReceiver.java").read_text(encoding="utf-8")
        checks = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DebugAsyncPlayerChecks.java").read_text(encoding="utf-8")
        probe = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/PlaybackHealthProbe.java").read_text(encoding="utf-8")
        server = (ROOT / "mcp/src/sagetv_dev_mcp/server.py").read_text(encoding="utf-8")
        script = (ROOT / "scripts/mcp_seek_suite.py").read_text(encoding="utf-8")
        self.assertIn("healthCheckPerformed", checks)
        self.assertIn("outputHealthy", checks)
        self.assertIn("videoRecovered", checks)
        self.assertIn("audioRecovered", checks)
        self.assertIn("videoStillAdvancing", checks)
        self.assertIn("audioStillAdvancing", checks)
        self.assertIn("videoRecoveryFrames", checks)
        self.assertIn("audioRecoveryHeadFrames", checks)
        self.assertIn("healthFailureReason", checks)
        self.assertIn("bufferingPollCount", checks)
        self.assertIn("audioDecoderChanged", checks)
        self.assertIn("videoDecoderReleaseDelta", checks)
        self.assertIn('verdict = "output_health"', server)
        self.assertIn("timeline_within_tolerance", server)
        self.assertIn("WARN: timeline landed outside numeric tolerance", script)
        self.assertIn("recovery-timeout-ms", script)
        self.assertIn("verify-playback-ms", script)
        # The probe is on-demand reflection, not permanent player analytics telemetry.
        self.assertIn("decoderCounters", probe)
        self.assertIn("audioTrack", probe)
        self.assertIn("getPlaybackHeadPosition", probe)
        self.assertIn("surface.isValid()", probe)
        self.assertNotIn("addAnalyticsListener", probe)
        self.assertNotIn("addListener", probe)

    def test_player_snapshot_includes_decoder_surface_and_audio_health(self):
        probe = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/PlaybackHealthProbe.java").read_text(encoding="utf-8")
        server = (ROOT / "mcp/src/sagetv_dev_mcp/server.py").read_text(encoding="utf-8")
        for key in (
            "videoDecoder", "videoDecoderKind", "videoRendered", "videoDropped",
            "audioDecoder", "audioDecoderKind", "audioRendered", "audioTrackState", "audioTrackPlayState", "audioPlaybackHeadFrames",
            "surfaceValid", "bufferedPositionMs", "playerError", "dataSourceClass", "videoDecoderInitCount", "audioDecoderInitCount",
        ):
            self.assertIn(key, probe)
        self.assertIn('"health_videoDecoder"', server)
        self.assertIn('"health_audioPlaybackHeadFrames"', server)
        self.assertIn('"health_surfaceValid"', server)

    def test_comskip_uses_direct_sagetv_right_left_and_records_recovery_landing(self):
        receiver = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DevTestReceiver.java").read_text(encoding="utf-8")
        checks = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DebugAsyncPlayerChecks.java").read_text(encoding="utf-8")
        player_commands = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DebugPlayerCommands.java").read_text(encoding="utf-8")
        adb = (ROOT / "mcp/src/sagetv_dev_mcp/adb.py").read_text(encoding="utf-8")
        server = (ROOT / "mcp/src/sagetv_dev_mcp/server.py").read_text(encoding="utf-8")
        script = (ROOT / "scripts/mcp_comskip_test.py").read_text(encoding="utf-8")
        devsh = (ROOT / "dev.sh").read_text(encoding="utf-8")
        # Dedicated debug Comskip path keeps real A/V recovery instrumentation but never injects an Android key.
        self.assertIn('"comskip".equals(op)', receiver)
        self.assertIn('"comskip_check".equals(op)', receiver)
        self.assertIn('DebugPlayerCommands.comskip(context, intent)', receiver)
        self.assertIn('EventRouter.postCommand(client, command);', player_commands)
        self.assertNotIn('MediaMappingPreferences videoMappings', receiver)
        self.assertIn('videoRecoveryTimelineMs', checks)
        self.assertIn('audioRecoveryTimelineMs', checks)
        self.assertIn('outputRecoveryTimelineMs', checks)
        self.assertIn('landingTimelineMs', checks)
        self.assertIn('def android_comskip_check(', adb)
        self.assertIn('self.dev_control(\n            "comskip_check"', adb)
        self.assertIn('direction=normalized', adb)
        self.assertIn('"directSageCommand": normalized', adb)
        self.assertIn('"inputPath": "android_debug_direct_sage_event"', adb)
        self.assertIn("debug APK's dedicated Comskip operation", server)
        self.assertIn('def dev_run_comskip_check(', server)
        self.assertIn('observation_complete_with_separate_media_recovery_outcome', server)
        self.assertIn('server_seek_observed', server)
        self.assertIn('afterServerSeekSequence > beforeServerSeekSequence', checks)
        self.assertIn('MCP COMSKIP HEALTH SUITE', script)
        self.assertIn('debug-direct Comskip:', script)
        self.assertIn('mcp-comskip-test', devsh)

    def test_debug_direct_automation_controls_bypass_android_key_injection(self):
        receiver = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DevTestReceiver.java").read_text(encoding="utf-8")
        checks = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DebugAsyncPlayerChecks.java").read_text(encoding="utf-8")
        player_commands = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DebugPlayerCommands.java").read_text(encoding="utf-8")
        lifecycle = (SHARED / "java/opensagetv/vibe/miniclient/android/UIActivityLifeCycleHandler.java").read_text(encoding="utf-8")
        adb = (ROOT / "mcp/src/sagetv_dev_mcp/adb.py").read_text(encoding="utf-8")
        server = (ROOT / "mcp/src/sagetv_dev_mcp/server.py").read_text(encoding="utf-8")
        self.assertNotIn('"input_text".equals(op)', receiver)
        self.assertNotIn('inputTextDirect(', receiver)
        self.assertNotIn('postKeyEvent((int) ch, 0, ch)', receiver)
        self.assertNotIn('inputTextViaAndroidKeyboardForDebug(', lifecycle)
        self.assertNotIn('KeyCharacterMap.VIRTUAL_KEYBOARD', lifecycle)
        self.assertNotIn('target.dispatchKeyEvent(event)', lifecycle)
        self.assertIn('"player_control".equals(op)', receiver)
        self.assertIn('"frame_step".equals(op)', receiver)
        self.assertIn('MediaCmd.MEDIACMD_FRAMESTEP', player_commands)
        self.assertIn('android_debug_media_command_28', player_commands)
        self.assertIn('player.play();', player_commands)
        self.assertIn('player.pause();', player_commands)
        self.assertIn('player.stop();', player_commands)
        self.assertIn('"seek_relative".equals(op)', receiver)
        self.assertIn('currentPlayerPositionMs(MediaCmd mediaCmd, MiniPlayerPlugin player)', player_commands)
        self.assertIn('requestedTargetPlayerMs', checks)
        self.assertNotIn('requestedTargetMs = beforeTimelineMs', checks)
        self.assertIn('player.seek(targetMs);', player_commands)
        self.assertIn('"relative_seek_check".equals(op)', receiver)
        self.assertIn('hideImeForDebug()', lifecycle)
        self.assertIn('def native_input_text(', adb)
        self.assertIn('self.dev_control("input_text_native", text=value)', adb)
        self.assertIn('def keyboard_input_text(', adb)
        self.assertIn('def direct_input_text(', adb)
        self.assertIn('def android_relative_seek_check(', adb)
        self.assertIn('def dev_run_relative_seek_check(', server)
        self.assertIn('android_debug_direct_player_relative_seek', server)

    def test_failure_checkpoint_captures_audio_and_crash_diagnostics(self):
        adb = (ROOT / "mcp/src/sagetv_dev_mcp/adb.py").read_text(encoding="utf-8")
        server = (ROOT / "mcp/src/sagetv_dev_mcp/server.py").read_text(encoding="utf-8")
        self.assertIn("def dumpsys_audio", adb)
        self.assertIn("def crash_log", adb)
        self.assertIn('"audio": Path(str(base) + "_audio.txt")', server)
        self.assertIn('"crash": Path(str(base) + "_crash.txt")', server)
        self.assertIn('"state": Path(str(base) + "_state.json")', server)


    def test_long_health_broadcasts_are_not_marked_foreground_and_audio_head_reset_is_supported(self):
        adb = (ROOT / "mcp/src/sagetv_dev_mcp/adb.py").read_text(encoding="utf-8")
        probe = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/PlaybackHealthProbe.java").read_text(encoding="utf-8")
        checks = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DebugAsyncPlayerChecks.java").read_text(encoding="utf-8")
        script = (ROOT / "scripts/mcp_seek_suite.py").read_text(encoding="utf-8")
        self.assertIn("foreground: bool = True", adb)
        self.assertIn('"skip_check",\n            foreground=False,', adb)
        self.assertIn('"comskip_check",\n            foreground=False,', adb)
        self.assertIn("audioHeadResetDetected", probe)
        self.assertIn("same AudioTrack/session", probe)
        self.assertIn("audioHeadResetDuringRecovery", checks)
        self.assertIn("PlaybackHealthProbe.Snapshot audioRecoveryBaseline", checks)
        self.assertIn("PlaybackHealthProbe.audioOutputAdvanced(audioRecoveryBaseline, latestHealth)", checks)
        self.assertIn("SKIP: rapid output-health stress", script)

    def test_seek_suite_can_repeat_rapid_fixture_stress_from_a_fixed_position(self):
        script = (ROOT / "scripts/mcp_seek_suite.py").read_text(encoding="utf-8")
        self.assertIn('parser.add_argument("--rapid-only"', script)
        self.assertIn('parser.add_argument("--rapid-repeats"', script)
        self.assertIn('parser.add_argument("--rapid-reset-ms"', script)
        self.assertIn('"dev_seek_time"', script)
        self.assertIn("Rapid stress recovery summary:", script)
        self.assertIn("mcp_rapid_output_health_repeat_", script)


    def test_session_control_connect_ui_start_and_exit_tools(self):
        receiver = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DevTestReceiver.java").read_text(encoding="utf-8")
        session_commands = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DebugSessionCommands.java").read_text(encoding="utf-8")
        connection = (ROOT / "source/dev/core/src/main/java/opensagetv/vibe/miniclient/MiniClientConnection.java").read_text(encoding="utf-8")
        state = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DebugStateProvider.java").read_text(encoding="utf-8")
        adb = (ROOT / "mcp/src/sagetv_dev_mcp/adb.py").read_text(encoding="utf-8")
        server = (ROOT / "mcp/src/sagetv_dev_mcp/server.py").read_text(encoding="utf-8")
        script = (ROOT / "scripts/mcp_session_test.py").read_text(encoding="utf-8")
        devsh = (ROOT / "dev.sh").read_text(encoding="utf-8")
        roots = (ROOT / "scripts/mcp_ui_roots.py").read_text(encoding="utf-8")
        self.assertIn("from mcp_ui_roots import is_automation_root", script)
        self.assertIn('AUTOMATION_ROOT_MENUS = {"main menu", "dynamic menu by nielm"}', roots)
        self.assertIn("def is_automation_root(state: dict)", roots)
        self.assertIn("def wait_automation_root(", roots)
        self.assertIn('"connect".equals(op)', receiver)
        self.assertIn('"exit".equals(op)', receiver)
        self.assertIn('"watch_server_file".equals(op)', receiver)
        self.assertIn('"set_live_channel".equals(op)', receiver)
        self.assertIn('getLastConnectedServer()', session_commands)
        self.assertIn('Intent.FLAG_ACTIVITY_NEW_TASK', session_commands)
        self.assertIn('client.closeConnection()', session_commands)
        self.assertIn('postVibeWatchFileEvent(', session_commands)
        self.assertIn('serverPath, fromBeginning', session_commands)
        self.assertIn('postVibeChannelSetEvent(channel)', session_commands)
        self.assertIn('VIBE_WATCH_FILE_EVENT_REPLY_TYPE = 230', connection)
        self.assertIn('VIBE_CHANNEL_SET_EVENT_REPLY_TYPE = 231', connection)
        self.assertIn('VIBE_WATCH_FILE_FROM_BEGINNING_EVENT_REPLY_TYPE = 232', connection)
        self.assertIn('VIBE_SEEK_EVENT_REPLY_TYPE = 233', connection)
        self.assertIn('"VIBE_CURRENT_CHANNEL".equals(propName)', connection)
        self.assertIn('public String getVibeCurrentChannel()', connection)
        self.assertIn('public long getVibeChannelAckSequence()', connection)
        self.assertIn('vibeChannelAckSequence++', connection)
        self.assertIn('getVibeCurrentChannel()', state)
        self.assertIn('getVibeChannelAckSequence()', state)
        self.assertIn('public boolean postVibeWatchFileEvent(String serverPath)', connection)
        self.assertIn('public boolean postVibeSeekEvent(final long targetMs)', connection)
        self.assertIn('DebugSessionCommands.seekServerTime(context, intent)', receiver)
        self.assertIn('postVibeSeekEvent(targetMs)', session_commands)
        self.assertIn('menuName', state)
        self.assertIn('popupName', state)
        self.assertIn('hasTextInput', state)
        self.assertIn('def connect_server(', adb)
        self.assertIn('def exit_session(', adb)
        self.assertIn('def dev_connect_server(', server)
        self.assertIn('def dev_exit_session(', server)
        self.assertIn('def dev_wait_for_ui(', server)
        self.assertIn('menu_present: bool | None = None', server)
        self.assertIn('stable_ms: int = 0', server)
        self.assertIn('def dev_wait_for_playback_started(', server)
        self.assertIn('def dev_reset_media_watch_state(', server)
        self.assertIn('confirmationRequired', server)
        self.assertIn('sagex.clear_watched(media_file_id)', server)
        self.assertIn('def dev_play_video(', server)
        self.assertIn('def dev_play_server_path(', server)
        self.assertIn('def dev_set_live_channel(', server)
        self.assertIn('"watch_server_file",', server)
        self.assertIn('restart_from_beginning="true" if restart_from_beginning else "false"', server)
        self.assertIn('def _is_resume_restart_prompt(', server)
        self.assertIn('def _resolve_resume_restart_prompt(', server)
        self.assertIn('resume_prompt = _resolve_resume_restart_prompt', server)
        self.assertIn('restart_from_beginning: bool = False', server)
        self.assertIn('"restart_from_beginning" if restart_from_beginning else "default_resume"', server)
        self.assertIn('"resumePrompt": resume_prompt', server)
        self.assertIn('"existing_playback_did_not_stop"', server)
        self.assertIn('SagexApiClient.discover(server_address)', server)
        self.assertIn('sagex.resolve_context(client_id)', server)
        self.assertIn('sagex.find_media(requested)', server)
        self.assertIn('sagex.watch(context, match.media_file_id)', server)
        self.assertIn('clientId', state)
        self.assertIn('uiContextHint', state)
        self.assertIn('STEP: apply playback settings before connection/video start', script)
        self.assertIn('tool_call(client, "clear_logcat", {}, timeout=30.0)', script)
        self.assertLess(
            script.index('tool_call(client, "clear_logcat"'),
            script.index('"dev_prepare_clean_start"'),
        )
        self.assertIn('STEP: connect SageTV server', script)
        self.assertIn('STEP: play video by name on this MiniClient', script)
        self.assertIn('--video-name', script)
        self.assertIn('--server-path', script)
        self.assertIn('--start-ms', script)
        self.assertIn('--smb-mappings', script)
        self.assertIn('"smb_mappings": args.smb_mappings', script)
        self.assertIn('call_dict(client, "dev_play_server_path"', script)
        self.assertIn('"restart_from_beginning": args.restart_from_beginning', script)
        self.assertIn('call_dict(client, "dev_seek_time"', script)
        self.assertIn('normalize_start("INITIAL")', script)
        self.assertIn('normalize_start(label)', script)
        self.assertIn('"STOP_PLAY: "', script)
        self.assertIn('"STOP_PLAY_RECOVERY: "', script)
        self.assertIn('"dev_wait_for_playback_started"', script)
        self.assertIn('"retained-session PLAY did not recover A/V', script)
        self.assertNotIn('--nav', script)
        self.assertIn('--exit', script)
        self.assertIn('mcp-session-test', devsh)

    def test_live_tv_gate_uses_only_explicit_verified_channels(self):
        script = (ROOT / "scripts/mcp_live_tv_test.py").read_text(encoding="utf-8")
        server = (ROOT / "mcp/src/sagetv_dev_mcp/server.py").read_text(encoding="utf-8")
        self.assertIn('default_test_value("live_channels", ["2.1", "5.1"])', script)
        self.assertIn('"gsyplayer"', script)
        self.assertIn('"gsy_engine": args.gsy_engine', script)
        self.assertIn('add_fixed_encoding_args(parser)', script)
        self.assertIn('**fixed_config', script)
        self.assertIn('call_dict(client, "dev_set_live_channel"', script)
        self.assertIn('"--current-channel-only"', script)
        self.assertIn('if args.current_channel_only:', script)
        self.assertIn('wait_for_av(client, args.timeout_s, args.verify_ms)', script)
        self.assertIn('result.get("confirmedChannel"', script)
        self.assertIn('"alreadyActive": True', server)
        self.assertIn('changed_channel == requested', server)
        self.assertIn('changed_flush_sequence > before_flush_sequence', server)
        self.assertIn('changed_ack_sequence > before_ack_sequence', server)
        self.assertIn('transition_confirmed = media_changed or flush_changed or ack_changed', server)
        self.assertNotIn('{"command": "ch_up"}', script)

    def test_fixed_mim_matrix_is_fail_closed_and_runs_gsy_system_last(self):
        script = (ROOT / "scripts/mcp_fixed_mim_matrix.py").read_text(encoding="utf-8")
        devsh = (ROOT / "dev.sh").read_text(encoding="utf-8")
        self.assertIn('"ff_2"', (ROOT / "source/dev/core/src/main/java/opensagetv/vibe/miniclient/SageCommand.java").read_text(encoding="utf-8"))
        self.assertIn('"--run-jump-health"', script)
        self.assertIn('"--run-stop-restart"', script)
        self.assertNotIn("args.media_file_id", script)
        self.assertNotIn("args.search_text", script)
        self.assertIn('"--require-captions"', script)
        self.assertIn('"--restart-from-beginning"', script)
        self.assertIn('key=lambda case: case.player == "gsyplayer" and case.gsy_engine == "system"', script)
        self.assertIn('def query_mim_status(', script)
        self.assertIn('"lastTranscodeJob"', script)
        self.assertIn('"hardwareEncode"', script)
        self.assertIn('no_orphan_jobs = isinstance(active_jobs, list) and len(active_jobs) == 0', script)
        self.assertIn('stopped_cleanly = str(job.get("state", "")) == "stopped"', script)
        self.assertIn('"noOrphanJobs": no_orphan_jobs', script)
        self.assertIn('"--require-mim-status"', script)
        self.assertIn('"--caption-gate"', script)
        self.assertIn('"SKIPPED_FIXTURE_HAS_NO_CUES"', script)
        self.assertIn('"captionGatePolicy": args.caption_gate', script)
        self.assertIn('return 0 if failures == 0 else 1', script)
        self.assertIn('"status": "SKIPPED"', script)
        self.assertIn('mcp-fixed-mim-test)', devsh)


    def test_native_end_to_end_playback_start_test_uses_explicit_server_and_exact_sequence(self):
        script = (ROOT / "scripts/mcp_playback_test.py").read_text(encoding="utf-8")
        devsh = (ROOT / "dev.sh").read_text(encoding="utf-8")
        self.assertIn('default=default_server_address()', script)
        self.assertIn('default="media3"', script)
        self.assertIn('default="push"', script)
        self.assertIn('default="hardware"', script)
        self.assertIn('"gsy_system_probe": args.gsy_system_probe', script)
        self.assertIn('"--gsy-system-probe"', script)
        self.assertIn('GSY SYSTEM PROBE: PASS', script)
        self.assertIn('fallback_count != 1', script)
        self.assertIn('"Media3MediaPlayerImpl" not in backend', script)
        server = (ROOT / "mcp/src/sagetv_dev_mcp/server.py").read_text(encoding="utf-8")
        self.assertIn('"gsyResolvedEngine", "gsySystemFallbackCount", "gsySystemFallbackReason"', server)
        self.assertIn('"save": False', script)
        self.assertIn('call_dict(client, "dev_connect_server"', script)
        self.assertIn('def start_recording_via_search(', script)
        self.assertIn('call_dict(client, "dev_open_search"', script)
        self.assertIn('"require_ime": False', script)
        self.assertIn('"suppress_ime": True', script)
        self.assertIn('call_dict(client, "dev_type_text"', script)
        self.assertIn('call_dict(client, "dev_hide_ime"', script)
        self.assertIn('"ime_not_visible"', script)
        self.assertIn('call_dict(\n                client, "dev_set_ime_suppression"', script)
        self.assertIn('textEntryVerification', script)
        self.assertNotIn('call_dict(client, "dev_sage_command_sequence"', script)
        self.assertIn('for command in ("right", "right", "right", "select"):', script)
        self.assertIn('"popup_contains": "option"', script)
        self.assertIn('select_resume_default', script)
        self.assertIn('"resume" in normalized_popup and "restart" in normalized_popup', script)
        self.assertIn('call_dict(client, "dev_sage_command"', script)
        self.assertIn('call_dict(client, "dev_wait_for_playback_started"', script)
        self.assertIn("from mcp_ui_roots import wait_automation_root", script)
        self.assertIn("ready = wait_automation_root(", script)
        self.assertIn("stable_ms=args.ui_stable_ms", script)
        self.assertIn('--ui-stable-ms', script)
        self.assertNotIn('call_dict(client, "dev_send_sequence", {"sequence": sequence}', script)
        self.assertNotIn('dev_play_video', script)
        self.assertIn('dev_play_server_path', script)
        self.assertNotIn('SagexApiClient', script)
        self.assertIn('mcp-playback-test)', devsh)

    def test_session_start_verifies_real_output_when_probe_supported(self):
        server = (ROOT / "mcp/src/sagetv_dev_mcp/server.py").read_text(encoding="utf-8")
        self.assertIn('def _stream_expectations(', server)
        self.assertIn('def _playback_health_from_pair(', server)
        self.assertIn('health_videoRendered', server)
        self.assertIn('health_audioPlaybackHeadFrames', server)
        self.assertIn('health_surfaceValid', server)
        self.assertIn('health_isPlaying', server)
        self.assertIn('def _wait_for_playback(', server)
        self.assertIn('expect_video: bool = True', server)
        self.assertIn('expect_audio: bool = True', server)
        self.assertIn('video_advancing and audio_advancing and surface_ok and no_error', server)
        self.assertIn('def _startup_terminal_failure(', server)
        self.assertIn('"code": "eof_delete_prompt"', server)
        self.assertIn('"code": "player_error"', server)
        self.assertIn('"code": "startup_output_timeout"', server)
        self.assertIn('"waitingForVideo"', server)
        self.assertIn('"waitingForAudio"', server)
        self.assertIn('def _dvd_static_menu_health(', server)
        self.assertIn('"verdict_basis": "dvd_static_menu"', server)
        self.assertIn('static_menu_healthy, static_menu_details = _dvd_static_menu_health(first)', server)
        disc_script = (ROOT / "scripts/mcp_disc_test.py").read_text(encoding="utf-8")
        self.assertIn('"--command-input"', disc_script)
        self.assertIn('possible_mode, possible_command = command.split(":", 1)', disc_script)
        self.assertIn('possible_mode.lower() in ("sage", "firetv")', disc_script)
        self.assertIn('call_dict(client, "firetv_key"', disc_script)
        self.assertIn('"--expect-audio-selector"', disc_script)
        self.assertIn('"--expect-subtitle-selector"', disc_script)
        self.assertIn('"--expect-media-time-min-ms"', disc_script)
        self.assertIn('"--expect-media-time-max-ms"', disc_script)
        self.assertIn('"--cadence-observe-s"', disc_script)
        self.assertIn("min(float(args.cadence_observe_s), 900.0)", disc_script)
        self.assertIn('"--min-realtime-ratio"', disc_script)
        self.assertIn('"--capture-datasource"', disc_script)
        self.assertIn('parser.add_argument("--start-ms"', disc_script)
        self.assertIn('parser.add_argument("--seek-tolerance-ms"', disc_script)
        self.assertIn('call_dict(client, "dev_server_seek_time"', disc_script)
        self.assertIn('abs(reached_ms - args.start_ms) <= args.seek_tolerance_ms', disc_script)
        self.assertIn('result["startSeek"]', disc_script)
        self.assertIn('"dev_set_datasource_capture"', disc_script)
        self.assertIn('"realtimeRatio": media_delta_ms / elapsed_ms', disc_script)
        self.assertIn('"DVD playback is slower than real time:', disc_script)
        self.assertIn('"dvdFrameReleaseGapCount"', disc_script)
        self.assertIn('state.get("dvdAppliedAudioStream", -1)', disc_script)
        self.assertIn('state.get("mediaTimeMs", -1)', disc_script)

    def test_completed_playback_lifecycle_gate_is_available(self):
        script = (ROOT / "scripts/mcp_lifecycle_test.py").read_text(encoding="utf-8")
        devsh = (ROOT / "dev.sh").read_text(encoding="utf-8")
        self.assertIn('call_dict(client, "firetv_key", {"key": "HOME"}', script)
        self.assertIn('call_dict(client, "launch_dev_app"', script)
        self.assertIn('dev_wait_for_playback_started', script)
        self.assertIn('def wait_automation_ready(', script)
        self.assertIn('wait_automation_root(client, timeout_s=timeout_s, stable_ms=2000)', script)
        self.assertIn('Foreground return created a second connection', script)
        self.assertIn('foreground return preserved the exact connection', script)
        self.assertIn('surface_released_or_hidden', script)
        self.assertIn('Foreground playback surface was not recreated', script)
        self.assertIn('dev_crash_probe', script)
        self.assertIn('{"stop_app": True}', script)
        self.assertIn('mcp-lifecycle-test)', devsh)

    def test_exact_eof_gate_is_available(self):
        script = (ROOT / "scripts/mcp_eof_test.py").read_text(encoding="utf-8")
        devsh = (ROOT / "dev.sh").read_text(encoding="utf-8")
        self.assertIn('"streaming": "pull"', script)
        self.assertIn('"dev_local_seek_absolute"', script)
        self.assertIn('health_playbackState', script)
        self.assertIn('AskToDeleteRecording', script)
        self.assertIn('dev_crash_probe', script)
        self.assertIn('mcp-eof-test)', devsh)

    def test_audio_focus_gate_is_available(self):
        script = (ROOT / "scripts/mcp_audio_focus_test.py").read_text(encoding="utf-8")
        devsh = (ROOT / "dev.sh").read_text(encoding="utf-8")
        self.assertIn('dev_request_competing_audio_focus', script)
        self.assertIn('dev_abandon_competing_audio_focus', script)
        self.assertIn('focus gain did not override an existing user pause', script)
        self.assertIn('permanent focus loss paused without an automatic resume', script)
        self.assertIn('mcp-audio-focus-test)', devsh)

    def test_comskip_gate_can_start_an_exact_server_path(self):
        script = (ROOT / "scripts/mcp_comskip_test.py").read_text(encoding="utf-8")
        self.assertIn('parser.add_argument("--server-path"', script)
        self.assertIn('"dev_prepare_clean_start"', script)
        self.assertIn('"dev_play_server_path"', script)
        self.assertIn('parser.add_argument("--start-ms"', script)
        self.assertIn('parser.add_argument("--start-tolerance-ms"', script)
        self.assertIn('parser.add_argument("--accept-auto-skip-on-position"', script)
        self.assertIn('parser.add_argument("--auto-skip-wait-ms"', script)
        self.assertIn("time.monotonic() < deadline", script)
        self.assertIn('parser.add_argument("--server-rewind-count"', script)
        self.assertIn('"commands": ["rew_2"]', script)
        self.assertIn("after server-owned positioning", script)
        self.assertIn('position_state.get("serverRequestedSeekMs"', script)
        self.assertIn('parser.add_argument("--summary-only"', script)
        self.assertIn("sourceFirstReadDeltaMs", script)
        self.assertIn("firstRenderedFrameDeltaMs", script)
        self.assertIn("auto_skip_observed = True", script)
        self.assertIn("automatic Comskip already exercised", script)
        self.assertIn('args.start_tolerance_ms', script)
        self.assertIn('parser.add_argument("--server-jump-count"', script)
        self.assertIn('parser.add_argument("--server-small-jump-count"', script)
        self.assertIn('"commands": ["ff_2"]', script)
        self.assertIn('"commands": ["ff"]', script)
        self.assertIn('"dev_wait_for_playback_started"', script)
        self.assertIn('positioned["eventualRecovery"] = eventual', script)
        self.assertIn('SageTV-owned positioning jump', script)
        self.assertIn('"dev_ensure_fullscreen_playback"', script)
        self.assertIn('fullscreen playback context established before Comskip', script)
        self.assertIn('"smb_direct", "smb_auto"', script)
        self.assertIn('parser.add_argument("--smb-mappings"', script)
        self.assertIn('player_config["smb_mappings"] = args.smb_mappings', script)
        self.assertIn('"dev_seek_time"', script)
        self.assertIn('recovered = bool(result.get("recovered"', script)
        self.assertIn('target_ok = result.get("target_within_tolerance") is not False', script)
        self.assertIn('"dev_exit_session"', script)

    def test_caption_gate_requires_real_non_empty_cues(self):
        script = (ROOT / "scripts/mcp_caption_test.py").read_text(encoding="utf-8")
        devsh = (ROOT / "dev.sh").read_text(encoding="utf-8")
        receiver = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DevTestReceiver.java").read_text(encoding="utf-8")
        state = (TV / "debug/java/opensagetv/vibe/miniclient/android/tv/debug/DebugStateProvider.java").read_text(encoding="utf-8")
        self.assertIn('"dev_set_subtitle_track"', script)
        self.assertIn('subtitleNonEmptyCueCount', script)
        self.assertIn('currentSubtitleCueText', script)
        self.assertIn('subtitleOverlayAttached', script)
        self.assertIn('"take_screenshot"', script)
        self.assertIn('parser.add_argument("--hold-s"', script)
        self.assertIn('"subtitle_control".equals(op)', receiver)
        self.assertIn('appendSubtitleState(out, player)', state)
        self.assertIn('mcp-caption-test)', devsh)

    def test_streaming_label_is_push_without_changing_persisted_value(self):
        arrays = (SHARED / "res/values/arrays.xml").read_text(encoding="utf-8")
        pref_store = (SHARED / "java/opensagetv/vibe/miniclient/android/prefs/AndroidPrefStore.java").read_text(encoding="utf-8")
        self.assertIn("<item>Push</item>", arrays)
        self.assertIn("<item>dynamic</item>", arrays)
        self.assertIn('STREAMING_MODE_DEFAULT = "dynamic";', pref_store)

    def test_main_settings_refresh_player_summaries_on_resume(self):
        settings = (SHARED / "java/opensagetv/vibe/miniclient/android/ui/settings/SettingsFragment.java").read_text(encoding="utf-8")
        strings = (SHARED / "res/values/strings.xml").read_text(encoding="utf-8")
        self.assertIn("refreshPlayerPreferenceSummaries();", settings)
        self.assertIn("public void onResume()", settings)
        self.assertIn("updateListSummary(decodingMethod, R.string.summary_list_decoding_method", settings)
        self.assertIn("Current: %s.", strings)


    def test_debug_readiness_and_clean_start_controls_exist(self):
        root = Path(__file__).resolve().parents[1]
        server = (root / "mcp/src/sagetv_dev_mcp/server.py").read_text(encoding="utf-8")
        adb = (root / "mcp/src/sagetv_dev_mcp/adb.py").read_text(encoding="utf-8")
        receiver = (root / "source/dev/android-tv/src/debug/java/opensagetv/vibe/miniclient/android/tv/debug/DevTestReceiver.java").read_text(encoding="utf-8")
        state = (root / "source/dev/android-tv/src/debug/java/opensagetv/vibe/miniclient/android/tv/debug/DebugStateProvider.java").read_text(encoding="utf-8")
        matrix = (root / "scripts/mcp_media3_matrix.py").read_text(encoding="utf-8")
        self.assertIn("def firetv_wake()", server)
        self.assertIn("def adb_session_status()", server)
        self.assertIn("persistent_shell_status", adb)
        self.assertIn("_persistent_shell_command", adb)
        self.assertIn("def dev_app_status()", server)
        self.assertIn("def kill_dev_app()", server)
        self.assertIn("def dev_prepare_clean_start(", server)
        self.assertIn("automation_ready: bool | None = None", server)
        self.assertIn("def prepare_clean_start", adb)
        self.assertIn('out.append(";uiState=")', state)
        self.assertIn('out.append(";automationReady=")', state)
        self.assertIn('out.append(";imeRequested=")', state)
        self.assertIn('out.append(";imeVisibleKnown=")', state)
        self.assertIn('out.append(";imeVisible=")', state)
        self.assertIn('out.append(";debugStatusVersion=21")', state)
        self.assertIn('out.append(";maxRecoveryWatchdogMs=")', state)
        ui_handler = (root / "source/dev/android-shared/src/main/java/opensagetv/vibe/miniclient/android/UIActivityLifeCycleHandler.java").read_text(encoding="utf-8")
        self.assertIn("getImeVisibilityForDebug()", ui_handler)
        self.assertIn("isKeyboardRequestedForDebug()", ui_handler)
        self.assertIn("setKeyboardSuppressedForDebug(boolean suppressed)", ui_handler)
        self.assertIn("isKeyboardSuppressedForDebug()", ui_handler)
        keyboard_state = (
            ROOT
            / "source/dev/android-shared/src/main/java/opensagetv/vibe/miniclient/android/UiKeyboardDebugState.java"
        ).read_text(encoding="utf-8")
        self.assertIn("visible && UiKeyboardDebugState.suppressed()", ui_handler)
        self.assertIn("WindowInsets.Type.ime()", keyboard_state)
        self.assertIn("WeakReference<Activity>", keyboard_state)
        self.assertIn("imeSuppressedForDebug", server)
        self.assertIn("imeVisibleKnown", server)
        self.assertIn("imeVisible", server)
        self.assertIn("static String configuredValues(PrefStore prefs)", state)
        self.assertIn("PlaybackHealthProbe.Snapshot health = PlaybackHealthProbe.capture(player);", state)
        self.assertIn('out.append(health.compactWire("health_"));', state)
        self.assertNotIn("appendPlaybackHealth(out, player);", receiver)
        self.assertIn('"dev_prepare_clean_start"', matrix)
        self.assertIn("from mcp_ui_roots import wait_automation_root", matrix)
        self.assertIn("ready = wait_automation_root(", matrix)
        roots = (root / "scripts/mcp_ui_roots.py").read_text(encoding="utf-8")
        self.assertIn('{"command": "home"}', roots)
        # Deterministic automation must direct-connect into the MiniClient UI; the generic
        # launcher opens ServersActivity and is reserved for manual MCP use.
        self.assertNotIn('"launch_dev_app"', matrix)
        playback = (root / "scripts/mcp_playback_test.py").read_text(encoding="utf-8")
        session = (root / "scripts/mcp_session_test.py").read_text(encoding="utf-8")
        self.assertIn("stable_ms=args.ui_stable_ms", playback)
        self.assertNotIn('"launch_dev_app"', playback)
        self.assertNotIn('"launch_dev_app"', session)
        self.assertIn('"dev_connect_server"', matrix)
        self.assertIn('"dev_app_status"', matrix)


    def test_generic_debug_seek_time_uses_av_output_counters_for_recovery(self):
        receiver = (ROOT / "source/dev/android-tv/src/debug/java/opensagetv/vibe/miniclient/android/tv/debug/DevTestReceiver.java").read_text(encoding="utf-8")
        player_commands = (ROOT / "source/dev/android-tv/src/debug/java/opensagetv/vibe/miniclient/android/tv/debug/DebugPlayerCommands.java").read_text(encoding="utf-8")
        server = (ROOT / "mcp/src/sagetv_dev_mcp/server.py").read_text(encoding="utf-8")
        self.assertIn('"seek_time".equals(op)', receiver)
        self.assertIn('target_ms is required', player_commands)
        self.assertIn('player.seek(targetMs)', player_commands)
        self.assertIn('def dev_seek_time(target_ms: int', server)
        self.assertIn('def dev_server_seek_time(target_ms: int', server)
        self.assertIn('reached_ms = _snapshot_media_time(last)', server)
        self.assertIn('def dev_show_active_player_adjustments()', server)
        self.assertIn('adb.seek_time(target_ms)', server)
        self.assertIn('_wait_for_playback(timeout_s=timeout_s, verify_ms=stable_ms)', server)
        self.assertIn('videoStillAdvancing', server)
        self.assertIn('audioStillAdvancing', server)
        self.assertIn('android_debug_seek_output_counter_recovery', server)
        self.assertIn('video_audio_output_counters_advancing_position_diagnostic_only', server)
        self.assertNotIn('position_snapped_away_from_target', server)
        self.assertNotIn('ready_but_outside_target_tolerance', server)



    def test_native_text_automation_matches_miniclient_keymap_encoding(self):
        receiver = (ROOT / "source/dev/android-tv/src/debug/java/opensagetv/vibe/miniclient/android/tv/debug/DevTestReceiver.java").read_text(encoding="utf-8")
        session_commands = (ROOT / "source/dev/android-tv/src/debug/java/opensagetv/vibe/miniclient/android/tv/debug/DebugSessionCommands.java").read_text(encoding="utf-8")
        adb = (ROOT / "mcp/src/sagetv_dev_mcp/adb.py").read_text(encoding="utf-8")
        server = (ROOT / "mcp/src/sagetv_dev_mcp/server.py").read_text(encoding="utf-8")
        script = (ROOT / "scripts/mcp_playback_test.py").read_text(encoding="utf-8")
        keymap = (ROOT / "source/dev/android-shared/src/main/java/opensagetv/vibe/miniclient/android/ui/keymaps/KeyMapProcessor.java").read_text(encoding="utf-8")
        self.assertIn('"input_text_native".equals(op)', receiver)
        self.assertIn('static String inputTextNative(', session_commands)
        self.assertIn('keyCode = Character.toUpperCase(ch);', session_commands)
        self.assertIn('modifiers = Keys.SHIFT_MASK;', session_commands)
        self.assertIn('keyCode = Keys.VK_SPACE;', session_commands)
        self.assertIn('postKeyEvent(keyCode, modifiers, ch)', session_commands)
        self.assertIn('postKeyEvent(toSend, androidToSageKeyModifier(event), (char) event.getUnicodeChar())', keymap)
        self.assertIn('def native_input_text(', adb)
        self.assertIn('self.dev_control("input_text_native", text=value)', adb)
        self.assertIn('def dev_input_text_native(', server)
        self.assertIn('def dev_set_ime_suppression(', server)
        self.assertIn('self.dev_control("ime_suppress"', adb)
        self.assertIn('"ime_suppress".equals(op)', receiver)
        self.assertIn('native = adb.native_input_text(requested)', server)
        self.assertIn('"miniclient_native_key_event"', server)
        self.assertIn('call_dict(client, "dev_open_search"', script)
        self.assertIn('"require_ime": False', script)
        self.assertIn('"suppress_ime": True', script)
        self.assertIn('call_dict(client, "dev_type_text"', script)
        self.assertIn('call_dict(client, "dev_hide_ime"', script)
        self.assertIn('"ime_not_visible"', script)
        self.assertIn('call_dict(\n                client, "dev_set_ime_suppression"', script)
        self.assertIn('deferred_until_recording_playback_starts', script)
        self.assertIn('--text-char-delay-ms', script)
        self.assertIn('default=0', script)
        self.assertIn('def dev_open_search(', server)
        self.assertIn('def dev_wait_for_ime(', server)



if __name__ == "__main__":
    unittest.main()


class MCPSearchCommandTests(unittest.TestCase):

    def test_explicit_multiline_mcp_send_sequence_exists(self):
        server = (ROOT / "mcp/src/sagetv_dev_mcp/server.py").read_text(encoding="utf-8")
        devsh = (ROOT / "dev.sh").read_text(encoding="utf-8")
        script = (ROOT / "scripts/mcp_send_sequence.py").read_text(encoding="utf-8")
        self.assertIn("def dev_send_sequence(sequence: str)", server)
        self.assertIn("parse_sequence_script(sequence)", server)
        self.assertIn('item.action == "command"', server)
        self.assertIn('item.action == "sendkey"', server)
        self.assertIn('item.action == "sendtext"', server)
        self.assertIn('item.action == "delay"', server)
        self.assertIn('item.action == "waittextinput"', server)
        self.assertIn('item.action in {"waitimevisible", "waitimehidden"}', server)
        self.assertIn('imeVisibleKnown', server)
        self.assertIn('imeVisible', server)
        self.assertIn('hasTextInput', server)
        self.assertIn("mcp-send-sequence)", devsh)
        self.assertIn('tool_call(\n            client,\n            "dev_send_sequence"', script)

    def test_search_is_first_class_mcp_tool_and_host_command(self):
        server = (ROOT / "mcp/src/sagetv_dev_mcp/server.py").read_text(encoding="utf-8")
        devsh = (ROOT / "dev.sh").read_text(encoding="utf-8")
        script = (ROOT / "scripts/mcp_search_test.py").read_text(encoding="utf-8")
        self.assertIn("def dev_search()", server)
        self.assertIn("def dev_type_text(", server)
        self.assertIn("def dev_search_text(", server)
        self.assertIn('adb.sage_command("search")', server)
        self.assertIn('def dev_input_text_keyboard(', server)
        self.assertIn('adb.keyboard_input_text(requested)', server)
        self.assertIn('adb.sage_command("select")', server)
        self.assertIn('submit: bool = False', server)
        self.assertIn('dismiss_keyboard: bool = True', server)
        self.assertIn('keyboard_dismiss_result = adb.hide_ime()', server)
        self.assertIn("mcp-search-test)", devsh)
        self.assertIn('tool_call(client, "adb_connect"', script)
        self.assertIn('"dev_search_text"', script)
        self.assertIn('parser.add_argument("--text", required=True', script)
        self.assertNotIn('default="meet the press"', script)
        self.assertIn('def dev_search_text(\n    text: str,', server)
        self.assertNotIn('text: str = "meet the press"', server)
        self.assertIn('default="down,right,right,right,play_pause,play_pause"', script)
        self.assertIn('post_commands', server)
        self.assertIn('post_keys', server)
        self.assertIn('play_pause', server)
        self.assertIn('adb.sage_command(command)', server)
        self.assertIn('adb.key_sequence(keys', server)
